from pathlib import Path
from typing import List, Tuple, Optional
from ereader.formats.base import Document, TOCItem, Page, UnsupportedFormatError

try:
    import mobi
except ImportError:
    mobi = None


class MobiParser(Document):
    """
    Parser for MOBI/AZW files.
    Depends on the 'mobi' library.
    """

    def __init__(self, path: Path):
        super().__init__(path)
        if mobi is None:
            raise UnsupportedFormatError("The 'mobi' library is not installed. Cannot parse MOBI files.")
        
        self._temp_dir: Optional[Path] = None
        self._html_content: str = ""
        self._load()

    def _load(self):
        try:
            # mobi.unpack returns a path to the unpacked HTML
            temp_path, opf_path = mobi.unpack(str(self.path))
            self._temp_dir = Path(temp_path)
            
            # Find the actual content file (usually .html or .xhtml)
            html_files = list(self._temp_dir.glob("*.html")) + list(self._temp_dir.glob("*.xhtml"))
            if html_files:
                self._html_content = html_files[0].read_text(encoding='utf-8', errors='replace')
            else:
                raise UnsupportedFormatError("No HTML content found in unpacked MOBI file.")
                
        except Exception as e:
            raise UnsupportedFormatError(f"Failed to parse MOBI: {e}")

    @property
    def title(self) -> str:
        return self.path.stem

    @property
    def author(self) -> str:
        return "Unknown"

    @property
    def format(self) -> str:
        return "MOBI"

    @property
    def toc(self) -> List[TOCItem]:
        return []

    @property
    def total_pages(self) -> int:
        return 1

    def get_page(self, index: int) -> Page:
        if index == 0:
            return Page(index=0, text="", html=self._html_content)
        raise IndexError("MOBI parser currently supports single-page view only")

    def get_html(self) -> str:
        return self._html_content

    def search(self, query: str) -> List[Tuple[int, str]]:
        return []


# TODO / EXTENSION POINTS:
# 1. Extract metadata from .opf file generated by mobi.unpack.
# 2. Cleanup resources (temp directory) after closing document.
# 3. Use 'kindleunpack' or similar for better TOC and structure extraction.
# 4. Implement paging by parsing the unpacked HTML.
